import type { BookingRecord } from "@/features/booking/types";
import { calendarStatusStyles, CALENDAR_END_MINUTES, CALENDAR_START_MINUTES, getEndTime, getEventPosition, getHalfHourSlots, HALF_HOUR_HEIGHT, timeToMinutes, toDateKey } from "@/features/calendar/utils";
import type { StaffItem } from "@/features/staff/types";

type DayViewProps = { date: Date; appointments: BookingRecord[]; staff: StaffItem[]; onSelect: (appointment: BookingRecord) => void };

export function DayView({ date, appointments, staff, onSelect }: DayViewProps) {
  const dateKey = toDateKey(date);
  const slots = getHalfHourSlots();
  const bodyHeight = ((CALENDAR_END_MINUTES - CALENDAR_START_MINUTES) / 30) * HALF_HOUR_HEIGHT;
  const visibleAppointments = appointments.filter((appointment) => appointment.date === dateKey && timeToMinutes(appointment.time) >= CALENDAR_START_MINUTES && timeToMinutes(appointment.time) <= CALENDAR_END_MINUTES);

  return <section className="mt-4 overflow-hidden rounded-2xl border border-[#dfe5da] bg-white"><div className="overflow-x-auto"><div style={{ minWidth: `${Math.max(760, 72 + staff.length * 220)}px` }}><div className="grid border-b border-[#dfe5da] bg-[#f8faf6]" style={{ gridTemplateColumns: `72px repeat(${staff.length}, minmax(220px, 1fr))` }}><div className="px-3 py-4 text-xs font-semibold text-[#8a9990]">Время</div>{staff.map((member) => <div key={member.id} className="flex items-center gap-2 border-l border-[#dfe5da] px-4 py-4"><span className="size-2.5 rounded-full" style={{ backgroundColor: member.calendarColor }} /><span className="text-sm font-semibold text-[#385145]">{member.name}</span></div>)}</div><div className="flex"><div className="relative w-[72px] shrink-0 text-xs text-[#8a9990]" style={{ height: `${bodyHeight + 20}px` }}>{slots.map((slot, index) => <span key={slot} className="absolute right-3 -translate-y-1/2" style={{ top: `${index * HALF_HOUR_HEIGHT}px` }}>{slot}</span>)}</div><div className="grid flex-1" style={{ gridTemplateColumns: `repeat(${staff.length}, minmax(220px, 1fr))` }}>{staff.map((member) => <div key={member.id} className="relative border-l border-[#dfe5da]" style={{ height: `${bodyHeight + 20}px`, backgroundImage: `repeating-linear-gradient(to bottom, transparent 0, transparent ${HALF_HOUR_HEIGHT - 1}px, #edf0ea ${HALF_HOUR_HEIGHT}px)` }}>{visibleAppointments.filter((appointment) => appointment.staffId === member.id).map((appointment) => { const position = getEventPosition(appointment.time, appointment.durationMinutes); return <button type="button" key={appointment.id} onClick={() => onSelect(appointment)} className={`absolute left-1.5 right-1.5 overflow-hidden rounded-lg border p-2 text-left shadow-sm transition hover:brightness-[.98] ${calendarStatusStyles[appointment.status]}`} style={{ top: `${Math.max(2, position.top + 2)}px`, height: `${position.height}px`, borderLeftWidth: "4px", borderLeftColor: member.calendarColor }}><span className="block truncate text-xs font-bold">{appointment.serviceName}</span><span className="mt-0.5 block truncate text-[11px] font-medium">{appointment.clientName}</span><span className="mt-0.5 block text-[10px] opacity-75">{appointment.time}–{getEndTime(appointment.time, appointment.durationMinutes)}</span></button>; })}</div>)}</div></div></div></div></section>;
}
