export {
  canChangeAppointmentStatus,
  canCreateAppointment,
  canDeleteAppointments,
  canEditAnySchedule,
  canEditAppointment,
  canEditStaffSchedule,
  canManageClients,
  canManageServices,
  canManageStaff,
  canViewAppointment,
  canViewClients,
  canViewStaffProfile,
  canViewStaffSchedule,
} from "./permissions";
